# Generated by Django 3.1.4 on 2021-01-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0012_compiledperson_tweeted'),
    ]

    operations = [
        migrations.AddField(
            model_name='eduuniversitaria',
            name='strComentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
