# Generated by Django 3.1.4 on 2021-01-20 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0015_compiledorg_postula_distrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoEleccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idHVCargoEleccion', models.IntegerField(blank=True, null=True, unique=True)),
                ('strCargoEleccion', models.CharField(blank=True, max_length=5, null=True)),
                ('intItemCargoEleccion', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('idOrgPolCargoElec', models.IntegerField(blank=True, null=True)),
                ('strOrgPolCargoElec', models.TextField(blank=True, null=True)),
                ('strAnioCargoElecDesde', models.CharField(blank=True, max_length=5, null=True)),
                ('idEstado', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('strUsuario', models.TextField(blank=True, null=True)),
                ('idCargoEleccion', models.IntegerField(blank=True, null=True)),
                ('strCargoEleccion2', models.TextField(blank=True, null=True)),
                ('strOrder', models.TextField(blank=True, null=True)),
                ('strComentario', models.TextField(blank=True, null=True)),
                ('election', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='votes.elections')),
                ('idHojaVida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='votes.hojavida')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='votes.person')),
            ],
        ),
    ]
