# Generated by Django 3.1.4 on 2021-01-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0016_cargoeleccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoeleccion',
            name='strAnioCargoElecHasta',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
