# Generated by Django 3.1.4 on 2021-01-21 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0017_cargoeleccion_straniocargoelechasta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idHVExpeLaboral', models.IntegerField(blank=True, null=True, unique=True)),
                ('intItemExpeLaboral', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('strCentroTrabajo', models.TextField(blank=True, null=True)),
                ('strOcupacionProfesion', models.TextField(blank=True, null=True)),
                ('strRucTrabajo', models.CharField(blank=True, max_length=20, null=True)),
                ('strDireccionTrabajo', models.TextField(blank=True, null=True)),
                ('strAnioTrabajoDesde', models.CharField(blank=True, max_length=5, null=True)),
                ('strAnioTrabajoHasta', models.CharField(blank=True, max_length=5, null=True)),
                ('strUbigeoTrabajo', models.CharField(blank=True, max_length=6, null=True)),
                ('strTrabajoPais', models.CharField(blank=True, max_length=255, null=True)),
                ('strTrabajoDepartamento', models.CharField(blank=True, max_length=255, null=True)),
                ('strTrabajoProvincia', models.CharField(blank=True, max_length=255, null=True)),
                ('strTrabajoDistrito', models.CharField(blank=True, max_length=255, null=True)),
                ('strTrabajoUbiDepartamento', models.CharField(blank=True, max_length=6, null=True)),
                ('strTrabajoUbiProvincia', models.CharField(blank=True, max_length=6, null=True)),
                ('strTrabajoUbiDistrito', models.CharField(blank=True, max_length=6, null=True)),
                ('idEstado', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('strUsuario', models.CharField(blank=True, max_length=255, null=True)),
                ('strOrder', models.TextField(blank=True, null=True)),
                ('election', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='votes.elections')),
                ('idHojaVida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='votes.hojavida')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='votes.person')),
            ],
        ),
    ]
