# Generated by Django 3.1.4 on 2021-01-22 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0019_cargopartidario'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenunciaOrganizacionPolitica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idHVRenunciaOP', models.IntegerField(blank=True, null=True)),
                ('intItemRenunciaOP', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('idOrgPolRenunciaOP', models.IntegerField(blank=True, null=True)),
                ('strOrgPolRenunciaOP', models.TextField(blank=True, null=True)),
                ('strAnioRenunciaOP', models.CharField(blank=True, max_length=5, null=True)),
                ('strFechaRegistro', models.CharField(blank=True, max_length=50, null=True)),
                ('idEstado', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('strUsuario', models.CharField(blank=True, max_length=255, null=True)),
                ('cadenaRenuncia', models.TextField(blank=True, null=True)),
                ('strOrder', models.TextField(blank=True, null=True)),
                ('strComentario', models.TextField(blank=True, null=True)),
                ('election', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='votes.elections')),
                ('idHojaVida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='votes.hojavida')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='votes.person')),
            ],
        ),
    ]
