# Generated by Django 3.1.4 on 2021-01-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0020_renunciaorganizacionpolitica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargoeleccion',
            name='strAnioCargoElecDesde',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cargoeleccion',
            name='strAnioCargoElecHasta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cargoeleccion',
            name='strCargoEleccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cargopartidario',
            name='strAnioCargoPartiDesde',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cargopartidario',
            name='strAnioCargoPartiHasta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cargopartidario',
            name='strUsuario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='strAnioTrabajoDesde',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='strAnioTrabajoHasta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='strRucTrabajo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='strTrabajoDepartamento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='strTrabajoDistrito',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='strTrabajoPais',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='strTrabajoProvincia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='strTrabajoUbiDepartamento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='strTrabajoUbiDistrito',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='strTrabajoUbiProvincia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='strUbigeoTrabajo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='strUsuario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='renunciaorganizacionpolitica',
            name='strAnioRenunciaOP',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='renunciaorganizacionpolitica',
            name='strFechaRegistro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='renunciaorganizacionpolitica',
            name='strUsuario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
