# Generated by Django 3.1.4 on 2021-01-23 19:54

from django.db import migrations, models

from votes.models import CompiledOrg, Person


def update_missing_region(apps, schema_editor):
    CompiledOrg.objects.filter(postula_distrito=' ').update(postula_distrito=None)
    Person.objects.filter(strPostulaDistrito=' ').update(strPostulaDistrito=None)

    CompiledOrg.objects.filter(postula_distrito__isnull=True).update(postula_distrito="NoDefinida")
    Person.objects.filter(strPostulaDistrito__isnull=True).update(strPostulaDistrito="NoDefinida")


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0021_auto_20210123_1954'),
    ]

    operations = [
        migrations.RunPython(update_missing_region),
    ]
